import { useCallback, useEffect, useState } from "react"
import { api } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const labels: Record<string,string> = { queued:"排队中", uploading:"上传中", done:"已完成", failed:"失败", rate_limited:"429 等待" }
export function MediaUploadQueuePage() {
  const [stats,setStats]=useState<Record<string,number>>({}); const [items,setItems]=useState<any[]>([]); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false); const [bookId,setBookId]=useState(""); const [chapterId,setChapterId]=useState(""); const [saveDir,setSaveDir]=useState(""); const [avatars,setAvatars]=useState<any[]>([]); const [selected,setSelected]=useState<string[]>([])
  const load=useCallback(async()=>{ const [s,l]=await Promise.all([api.mediaQueue.stats(),api.mediaQueue.list({status})]); setStats(s); setItems(l.items || []) },[status])
  useEffect(()=>{ const initial=window.setTimeout(()=>{ void load() },0); const timer=window.setInterval(()=>{ void load() },5000); return ()=>{ window.clearTimeout(initial); window.clearInterval(timer) } },[load])
  const retry=async(id:number)=>{ await api.mediaQueue.retry(id); await load() }
  const retryFailed=async()=>{ setBusy(true); try { await api.mediaQueue.retryFailed(); await load() } finally { setBusy(false) } }; const loadAvatars=async()=>{ const result=await api.mediaQueue.avatars(bookId,chapterId,saveDir); setAvatars(result.items || []); setSelected([]) }; const enqueueAvatars=async()=>{ await api.mediaQueue.enqueueAvatars(bookId,saveDir,selected); await load() }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-slate-900">媒体上传队列</h1><p className="mt-1 text-sm text-slate-500">仅上传下载器已落盘文件；未完成项不会暴露本地或源站 URL。</p></div>
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{["queued","uploading","done","failed","rate_limited"].map(key=><Card key={key} className="cursor-pointer" onClick={()=>setStatus(status===key?"":key)}><CardHeader className="pb-2"><CardTitle className="text-sm">{labels[key]}</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{stats[key] || 0}</CardContent></Card>)}<Card><CardHeader className="pb-2"><CardTitle className="text-sm">并发</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{stats.active || 0}/{stats.concurrency || 0}</CardContent></Card></div>
    <div className="flex items-center gap-3"><Button variant="outline" disabled={busy} onClick={()=>void retryFailed()}>重试失败/429</Button><Button variant="ghost" onClick={()=>void load()}>刷新</Button>{status && <span className="text-sm text-slate-500">筛选：{labels[status]}</span>}</div>
    <Card><CardHeader><CardTitle>按章选择头像</CardTitle></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-4"><input className="rounded-md border p-2 text-sm" placeholder="书籍 ID" value={bookId} onChange={e=>setBookId(e.target.value)} /><input className="rounded-md border p-2 text-sm" placeholder="章节 ID" value={chapterId} onChange={e=>setChapterId(e.target.value)} /><input className="rounded-md border p-2 text-sm" placeholder="下载器 save_dir" value={saveDir} onChange={e=>setSaveDir(e.target.value)} /><Button variant="outline" onClick={()=>void loadAvatars()}>读取头像</Button></div>{avatars.length>0 && <div className="mt-4 space-y-2">{avatars.map(item=><label key={item.sourceUrl} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(item.sourceUrl)} onChange={e=>setSelected(e.target.checked?[...selected,item.sourceUrl]:selected.filter(url=>url!==item.sourceUrl))} /><span>{item.userName || "匿名"}</span><span className="truncate text-slate-500">{item.alreadyUploadedUrl ? "已上传" : "可上传"}</span></label>)}<Button className="mt-2" disabled={!selected.length} onClick={()=>void enqueueAvatars()}>批量加入上传（{selected.length}）</Button></div>}</CardContent></Card><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">书籍</th><th className="p-3">类型</th><th className="p-3">状态</th><th className="p-3">尝试</th><th className="p-3">错误</th><th className="p-3">操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-b last:border-0"><td className="p-3 font-mono">{item.book_id}</td><td className="p-3">{item.kind}</td><td className="p-3">{labels[item.status] || item.status}</td><td className="p-3">{item.attempts}</td><td className="max-w-xs truncate p-3 text-rose-600">{item.error || (item.status === "done" ? "" : "—")}</td><td className="p-3">{["failed","rate_limited"].includes(item.status) && <Button size="sm" variant="outline" onClick={()=>void retry(item.id)}>重试</Button>}</td></tr>)}{items.length===0 && <tr><td colSpan={6} className="p-8 text-center text-slate-500">暂无队列项</td></tr>}</tbody></table></div></CardContent></Card>
  </div>
}